spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedHeaders:
              - Content-Type
            allowedCredentials: false
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              
      routes[0]:
        id: alumnowebflux
        predicates: Path=/api/alumnowebflux/**
        filters: StripPrefix=2
        uri: lb://alumnowebflux
      routes[1]:
        id: singularidad
        predicates: Path=/api/singularidad/**
        filters: StripPrefix=2
        uri: lb://singularidad
      routes[2]:
        id: cursos
        predicates: Path=/api/cursos/**
        filters: StripPrefix=2
        uri: lb://cursos
      routes[3]:
        id: examenes
        predicates: Path=/api/examenes/**
        filters: StripPrefix=2
        uri: lb://examenes
      routes[4]:
        id: respuestas
        predicates: Path=/api/respuestas/**
        filters: StripPrefix=2
        uri: lb://respuestas

        
      discovery:
        locator:
          enabled: 'true'
    loadbalancer:
      ribbon:
        enabled: 'false'
  application:
    name: gateway

server:
  port: '8090'

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka
  
